sizes: [16, 32, 48, 64, 96, 128, 192, 256, 384, 512, 768, 1024, 1536, 2048, "all"]
batch_sizes: [16, 16, 16, 16, 32, 32, 32, 32, 64, 64, 64, 64, 64, 64, 64]
model_ids: 
  - "google-bert/bert-base-uncased"
  - "FacebookAI/roberta-base"
  - "microsoft/deberta-v3-base"
experiments: 
  - "vanilla"
  - "adding_synthetic_no_flip"
  - "backtranslation-cn-es-de"
  - "nlpaug-substitute_char"
  - "nlpaug-swap_char"
  - "nlpaug-delete_char"
  - "nlpaug-swap_word"
  - "nlpaug-delete_word"
  - "nlpaug-substitute_wordnet"
  - "nlpaug-insert_bert"
  - "nlpaug-substitute_bert"
  - "auggpt_single_turn" 
